### ISSUE TITLE
joinc 오타리포터로 활동(?)중인 ryon입니다. :)

### ISSUE THREAD

**Issue by ryonjeong** [yundream/gowiki#1]
안녕하세요 joinc 오타리포터로 활동 중인 ryon입니다. 

저도 개인적으로 10년 정도 사용 중인 moniwiki에서 gowiki로 넘어가 보고 싶어서 모니터링(?) 중인데요. 언제쯤 알파버전이라도 받아서 테스트 해 볼 수 있을까요? :-) 

감사합니다.

**Comment by yundream** [comment]
안녕하세요... 저도 가능하면 빨리 완성하고 싶기는 한데요...
귀차니즘 때문에 언제가 될지 모르겠네요 -.-;
일단 현재 상황은 문서의 저장, 읽기(wiki 문법 파싱후), plugin 등 기본적인 것들은 돌아갑니다.
여기에 유저 인증, 관리페이지 등을 만들어야 하는데.. 음..
어떡해서든 올해는 마무리 하도록 해보겠습니다.. ..
사실 지금 joinc가 gowiki 기반으로 돌고 있기는 합니다. 이번 버전은 go1.8에 맞춰서 그리고 공개 할 수 있는 수준으로 깔끔하게 정리하려는 목적이고요. 그러니까 마음만 먹으면 비교적 빠르게 개발이 가능하긴 한데.. 그 마음 먹기가. ...

아.. 참고로 저도 moniwiki 를 기반으로 해서 새로 개발을 했는데요. 아시겠지만 moniwiki에 보면 쓸데없이 많은 수의 문법적 기능들이 있습니다. 어차피 사용하는 건 별로 없는데 말입니다.
그래서 gowiki는 필요한 문법들만 지원하고 있습니다. markdown에서 지원하는 문법 수준이라고 보시면 됩니다.

**Comment by ryonjeong** [comment]
ㅎㅎ 네. 저도 써보니 쓰는게 toc, footnote, header, link, image 말곤 쓰지 않게 되더라구요. 모니터링(?)하고 있으니 언젠가 커밋하시면 들어와서 테스트 해보겠습니다.
